const theme = {
  light: {
    colors: {
      primary: '#ed8936',
      primaryStrong: '#744210',
      primaryStronger: '#7b341e',
      whiteyPrimary: '#feebc8',
      whitierPrimary: '#fffaf0',
      secondary: '#058AA1',
      secondaryStrong: '#37D3ED',
      secondaryStronger: '#057CA1',
      panels: '#ffffff',
      background: '#7b341e',
      gradient: {
        from: '#ff8e2f',
        to: '#ffbf4f',
      },
      sectionTitle: '#2d3748',
      boxShadow: '0px 1px 10px 4px #ddd',
      boxShadowHover: '0px 1px 10px 1px #ddd',
      secondaryBoxShadow: '0px 1px 10px 4px #ddd',
      secondaryBoxShadowHover: '0px 1px 10px 1px #ddd',
    },
    classes: {
      primary: 'orange-500',
      primaryStrong: 'orange-800',
      primaryStronger: 'orange-900',
      whiteyPrimary: 'orange-200',
      whitierPrimary: 'orange-100',
      secondary: 'blue-500',
      secondaryStrong: 'blue-600',
      secondaryStronger: 'blue-900',
      panels: 'white',
      background: 'orange-500',
      sectionTitle: 'gray-800',
      sectionCaption: 'gray-600',
      paragraph: 'gray-900',
      menuHover: 'orange-600',
      featuredPanel1: 'red-100',
      featuredPanel2: 'orange-100',
      footerBottomBackground: 'gray-200',
    },
  },
  dark: {
    colors: {
      primary: '#ed8936',
      primaryStrong: '#744210',
      primaryStronger: '#7b341e',
      whiteyPrimary: '#feebc8',
      whitierPrimary: '#fffaf0',
      secondary: '#058AA1',
      secondaryStrong: '#37D3ED',
      secondaryStronger: '#057CA1',
      panels: '#1a202c',
      background: '#7b341e',
      gradient: {
        from: '#ff8e2f',
        to: '#ffbf4f',
      },
      sectionTitle: '#2d3748',
      boxShadow: '0px 1px 10px 4px #da7f33',
      boxShadowHover: '0px 1px 10px 1px #da7f33',
      secondaryBoxShadow: '0px 1px 10px 4px #63b3ed',
      secondaryBoxShadowHover: '0px 1px 10px 1px #63b3ed',
    },
    classes: {
      primary: 'orange-500',
      primaryStrong: 'orange-800',
      primaryStronger: 'orange-900',
      whiteyPrimary: 'orange-200',
      whitierPrimary: 'orange-100',
      secondary: 'blue-500',
      secondaryStrong: 'blue-600',
      secondaryStronger: 'blue-900',
      panels: 'gray-900',
      background: 'orange-500',
      sectionTitle: 'gray-500',
      sectionCaption: 'orange-300',
      paragraph: 'gray-200',
      menuHover: 'orange-600',
      footerBottomBackground: 'gray-800',
    },
  },
};

export default theme;
